// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaiVuge1Q-puhcTGs1RRH_PtRC4I-nMk',
    appId: '1:674298603160:web:17b9d443e5f894e35092ed',
    messagingSenderId: '674298603160',
    projectId: 'myfirebasedemoapp-1333e',
    authDomain: 'myfirebasedemoapp-1333e.firebaseapp.com',
    storageBucket: 'myfirebasedemoapp-1333e.appspot.com',
    measurementId: 'G-J1W4DJ1FNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA206U1yCTAh0lv3xFVlosn6Zci1koH5QA',
    appId: '1:674298603160:android:3d4ce7490da522b65092ed',
    messagingSenderId: '674298603160',
    projectId: 'myfirebasedemoapp-1333e',
    storageBucket: 'myfirebasedemoapp-1333e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ZNxEfKiyZSFJtVbCZ5ld9yfCcePKeNk',
    appId: '1:674298603160:ios:1f2423ffb9359d9a5092ed',
    messagingSenderId: '674298603160',
    projectId: 'myfirebasedemoapp-1333e',
    storageBucket: 'myfirebasedemoapp-1333e.appspot.com',
    iosBundleId: 'com.toangtv.myFirebaseDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ZNxEfKiyZSFJtVbCZ5ld9yfCcePKeNk',
    appId: '1:674298603160:ios:1f2423ffb9359d9a5092ed',
    messagingSenderId: '674298603160',
    projectId: 'myfirebasedemoapp-1333e',
    storageBucket: 'myfirebasedemoapp-1333e.appspot.com',
    iosBundleId: 'com.toangtv.myFirebaseDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdaiVuge1Q-puhcTGs1RRH_PtRC4I-nMk',
    appId: '1:674298603160:web:e08af1000e3355da5092ed',
    messagingSenderId: '674298603160',
    projectId: 'myfirebasedemoapp-1333e',
    authDomain: 'myfirebasedemoapp-1333e.firebaseapp.com',
    storageBucket: 'myfirebasedemoapp-1333e.appspot.com',
    measurementId: 'G-5FZ7HMCT5E',
  );
}
